# This is a basic workflow to help you get started with Actions

name: Action for jdsd-helper

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 9 * * *' # Clock in at 9:00 CST everyday.
  workflow_dispatch:  # manually dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Execute jdsd-helper
        env:
            jdsd_key: "V1M9+H/LyOPAFVhWZrVVkSAgf3qe3/zjMoghkpcPvdWgVhAc/ze3NdxHye1PIagd"
        run: yarn start
      
